### ISSUE TITLE
Empty gas report table since Hardhat migration

### ISSUE THREAD

**Issue by paulrberg** [cgewecke/hardhat-gas-reporter#55] opened 2020-12-29 18:35 UTC
## Description

When I was using this tool with Buidler, it was working. I was seeing the gas report at the end of my my test suite execution.

But now ..

<img width="688" alt="Capture d’écran 2020-12-29 à 20 33 49" src="https://user-images.githubusercontent.com/8782666/103305989-29252180-4a15-11eb-842b-b6b4a4bd62a5.png">

## Steps to Reproduce

1. git clone git@github.com:MainframeHQ/mainframe-lending-protocol.git
2. cd mainframe-lending-protocol
3. git checkout 72fb114
4. yarn install
5. REPORT_GAS=true yarn test:unit 

## Environment

+ hardhat@2.0.3
+ hardhat-gas-reporter@1.0.1

**Comment by cgewecke** [comment] 2020-12-29 18:37
@paulrberg If you upgrade to `1.0.4` do you get anything?

**Comment by paulrberg** [comment] 2020-12-29 18:42
Unfortunately, no. I upgraded to `1.0.4` and I ran it with both hardhat@2.0.3 and hardhat@2.0.6, hoping that there may be an incompatibility with Hardhat itself. None worked.

See [f2943ca](https://github.com/MainframeHQ/mainframe-lending-protocol/commit/f2943ca69a489eeda022226db65b0758b98a5d22).

**Comment by cgewecke** [comment] 2020-12-29 18:43
Ok cool, will take a look. Thanks for reporting.

**Comment by cgewecke** [comment] 2020-12-29 19:37
Weirdly, it looks like a problem caused by having `eth-gas-reporter` as a [separately listed dependency][1]. If you remove that and let `hardhat-gas-reporter` manage the version transitively I think it should work...

[1]: https://github.com/MainframeHQ/mainframe-lending-protocol/blob/f2943ca69a489eeda022226db65b0758b98a5d22/package.json#L47

`0.2.18` is getting installed as outer-most in node_modules instead of `0.2.20`.  Mocha loads the reporter itself and just grabs the first thing it sees.  

I was able to get this after making sure `0.2.20` is outermost. (Partial shot...)

![Screen Shot 2020-12-29 at 11 14 34 AM](https://user-images.githubusercontent.com/7332026/103309280-8bf0cb80-49c9-11eb-8063-d15017793257.png)

**Comment by cgewecke** [comment] 2020-12-29 19:43
At a minimum, should probably add a note in the README about uninstalling eth-gas-reporter when migrating from Truffle...

**Comment by paulrberg** [comment] 2020-12-30 16:23
Hmm, interesting. If I recall correctly the reason why I installed `eth-gas-reporter` is because yarn was complaining that `buidler-gas-reporter` (at the time) was lacking a peer dependency.

Now it works! I'll let you decide when to close this issue (in case you want to add the caveat in the README).

**Comment by cgewecke** [comment] 2021-01-01 18:02
Addressed in 97258f9. Thanks Paul!

**Closed by cgewecke** 2021-01-01 18:02 UTC
