### ISSUE TITLE
Price data missing from report

### ISSUE THREAD

**Issue by feuGeneA** [cgewecke/hardhat-gas-reporter#72] opened 2021-08-18 16:17 UTC
I just finished integrating `hardhat-gas-reporter` into a new Advanced Sample Project that can be generated by the project initialization feature of the `hardhat` command-line interface.  See https://github.com/nomiclabs/hardhat/pull/1632

However, I could not get the price data to show in the output.  Re-posting from [a comment on that PR](https://github.com/nomiclabs/hardhat/pull/1632#issuecomment-897074126):

> > * Running with eth gas reporter doesn't show anything in the USD column. Why does this happen? Maybe some missing config? Can we maybe remove it / use ETH?

> I spent an hour trying to figure this out.  I couldn't get it to work.

> I tried removing the currency from the config, and that made it default to EUR, but it still didn't have any price data.  I also tried changing the config to `currency: "ETH"`, but that didn't result in any meaningful data either.  I also tried getting a CoinMarketCap API key and plugging it into the config, but that didn't help either.

> I even went in and debugged `eth-gas-station`, adding a `console.log()` statements to just before [the call to coinmarketcap](https://github.com/cgewecke/eth-gas-reporter/blob/master/lib/utils.js#L189) and just after.  The one just before showed that the URL it was hitting was just fine (I pulled the url via `curl` and the data looks fine/legit to me (no error conditions or anything, and expected object fields seem fine)), but the `console.log()` statement just *after* the CMC call never gets executed, and I gave up on trying to figure out why.

For easy reference:
* the config in use: https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/sample-projects/advanced/hardhat.config.js#L36
* results from the CI run: https://github.com/nomiclabs/hardhat/runs/3313026188#step:6:831

And here's a paste of the output I'm seeing:

```
·----------------------------|----------------------------|-------------|-----------------------------·
|    Solc version: 0.8.4     ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 30000000 gas  │
·····························|····························|·············|······························
|  Methods                                                                                            │
·············|···············|··············|·············|·············|···············|··············
|  Contract  ·  Method       ·  Min         ·  Max        ·  Avg        ·  # calls      ·  usd (avg)  │
·············|···············|··············|·············|·············|···············|··············
|  Greeter   ·  setGreeting  ·           -  ·          -  ·      35426  ·            2  ·          -  │
·············|···············|··············|·············|·············|···············|··············
|  Deployments               ·                                          ·  % of limit   ·             │
·····························|··············|·············|·············|···············|··············
|  Greeter                   ·           -  ·          -  ·     497002  ·        1.7 %  ·          -  │
·----------------------------|--------------|-------------|-------------|---------------|-------------·
```

Reproducing would be easy if you checked out and built the hardhat monorepo and then in an empty folder did `yarn init --yes && yarn add --file:/path/to/monorepo/packages/hardhat-core && yarn hardhat` and selected "advanced project" and then did `REPORT_GAS=true yarn hardhat test`.  And it would be even easier than that if you were to wait until this functionality is officially released.

Please let me know if this is my error or if I'm having the wrong expectations.

Thank you!

**Comment by cgewecke** [comment] 2021-08-28 20:10
Added tests for this in #73 ... seems like it's working ok. Not sure what happened here.

**Comment by cgewecke** [comment] 2021-08-28 20:21
Ah!! I think the problem is that the prices are fetched async at `eth-gas-reporter` and the mocha reporter hooks are sync.  Usually this doesn't matter because the call resolves by the time the tests have run and are available when report is generated in the final hook. 

Your tests for the sample project are probably completing more or less instantly. 

To fix this case we'd need to fetch prices in this plugin where running async logic before the tests is supported.

**Comment by feuGeneA** [comment] 2021-08-31 18:30
Thank you @cgewecke for the attention to this.  Is there any recommended change to my tests?  Or do you mean that this is something that needs to change in the plugin?  Or something else?

**Comment by cgewecke** [comment] 2021-08-31 19:44
@feuGeneA 

I think you *could* get price data by introducing a small delay in your "internal" hh test [here][1]. 

But ultimately the problem is a race-condition in eth-gas-reporter and the sync-ness of mocha's third-party reporter api. This race-condition shouldn't affect most people though - their test suites typically run longer than the latency of the CMC request. 

To fix I will need to fetch the price in `TASK_TEST_RUN_MOCHA_TESTS` here and create a configuration option at eth-gas-reporter for this data. 

Sorry about this...I'm sure it was annoying to debug 😅  

[1]: https://github.com/nomiclabs/hardhat/blob/e29e14c7edf6edf405cab31bad09c98660794210/packages/hardhat-core/sample-projects/advanced-ts/test/index.ts#L4-L17

**Comment by grapevinegizmos** [comment] 2021-10-29 22:37
Just to note I am having same problem.  No prices in USD column are reported, although I can see on CoinMarketCap that the api is being hit when I run tests.

**Comment by piotr-dajlido** [comment] 2021-11-18 19:38
For me it was setting
` await delay(500); // ofc for you it might be 250 or even 1200 depending on your internet connection` 
before any `expect()`
```
        await marketplace.connect(company).addMarketItem(nft.address, BigNumber.from(1), toWei('500.50'));
        const companyNfts: MarketItemStructOutput[] = await marketplace.connect(company).fetchMarketItems();

        await delay(500); // <-- Here!
        expect(companyNfts.length).equal(1);
        expect(companyNfts[0]['seller']).equal(company.address);
        expect(companyNfts[0]['itemId']).equal(1);
```
Nonethereless @cgewecke looking forward to more elegant solution.
Cheers!

**Comment by EmanHerawy** [comment] 2021-11-21 15:19
I have managed to fix it, for me, it was because of `ethereum-waffle`  https://hardhat.org/guides/waffle-testing.html#adapting-the-tests
now it works like a charm

**Comment by cgewecke** [comment] 2021-11-29 17:02
This should be fixed now in #1.0.5 via #80.

**Closed by cgewecke** 2021-11-29 17:02 UTC
Labels: Investigate

**Comment by kazazor** [comment] 2021-12-06 10:11
Hi @cgewecke :)
I'm using version `1.0.6` and still do not see any USD information
<img width="1199" alt="Screen Shot 2021-12-06 at 12 10 55" src="https://user-images.githubusercontent.com/1577655/144827828-5d1d264a-0bc3-4d08-8daf-1bb010bfca33.png">
:

I have a simple set of tests (about 12 at the moment) and a very simple configuration:
```js
  gasReporter: {
    currency: "USD",
    gasPrice: 90,
  },
```

was this truly fixed? Should I do something else here?

**Comment by cgewecke** [comment] 2021-12-06 13:18
@kazazor I think you'll need to get your own free-tier [coinmarketcap api key, here][1] and set the option in your config:

[1]: https://coinmarketcap.com/api/pricing/

```ts
gasReporter: {
    currency: "USD",
    coinmarketcap: "abcde-....",
    gasPrice: 90,
  },
```

The limit on the shared key is not per plugin user but rather for all users of the plugin. It's rate limited almost instantly now that the package is widely used ... you have to have your own credentials for price reporting to work unfortunately.

**Comment by kazazor** [comment] 2021-12-06 13:44
My bad here, thought it's shared for some reason :) It works, thanks!

**Comment by pawnfi-rhynie** [comment] 2022-01-04 07:49
> @kazazor I think you'll need to get your own free-tier [coinmarketcap api key, here](https://coinmarketcap.com/api/pricing/) and set the option in your config:
> 
> ```ts
> gasReporter: {
>     currency: "USD",
>     coinmarketcap: "abcde-....",
>     gasPrice: 90,
>   },
> ```
> 
> The limit on the shared key is not per plugin user but rather for all users of the plugin. It's rate limited almost instantly now that the package is widely used ... you have to have your own credentials for price reporting to work unfortunately.
> 
> Just lmk if doing that doesn't work and I will re-open this issue and investigate.
I configured the coinmarketcap api key, but the usd price is still not displayed. Is it because of the free api key?

**Comment by Rhynie** [comment] 2022-01-04 07:50
> @kazazor I think you'll need to get your own free-tier [coinmarketcap api key, here](https://coinmarketcap.com/api/pricing/) and set the option in your config:
> 
> ```ts
> gasReporter: {
>     currency: "USD",
>     coinmarketcap: "abcde-....",
>     gasPrice: 90,
>   },
> ```
> 
> The limit on the shared key is not per plugin user but rather for all users of the plugin. It's rate limited almost instantly now that the package is widely used ... you have to have your own credentials for price reporting to work unfortunately.
> 
> Just lmk if doing that doesn't work and I will re-open this issue and investigate.




I configured the coinmarketcap api key, but the usd price is still not displayed. Is it because of the free api key?

**Comment by cgewecke** [comment] 2022-01-04 12:58
@Rhynie If you are using your own api key you obtained from coinmarketcap it should work.

Are you sure you've configured the options correctly?

**Comment by Rhynie** [comment] 2022-01-04 13:05
> 

![image](https://user-images.githubusercontent.com/43163156/148063282-f85d12bd-4484-45d0-8999-7d2d31eb6f5e.png)
![image](https://user-images.githubusercontent.com/43163156/148063407-4a825cda-7b43-423b-a88d-588d75aa72a5.png)

This is my configuration file.

**Comment by Rhynie** [comment] 2022-01-04 13:09
> > 
> 
> ![image](https://user-images.githubusercontent.com/43163156/148063282-f85d12bd-4484-45d0-8999-7d2d31eb6f5e.png) ![image](https://user-images.githubusercontent.com/43163156/148063407-4a825cda-7b43-423b-a88d-588d75aa72a5.png)
> 
> This is my configuration file.

@cgewecke can you help me?

**Comment by cgewecke** [comment] 2022-01-04 13:11
@Rhynie Are you using the latest version? Your test suite is very short ... prior to v1.0.6 the plugin had a race condition when fetching remote data that caused price info to be missing from the report if tests completed before the coinmarketcap api call resolved.

**Comment by Rhynie** [comment] 2022-01-04 13:18
![image](https://user-images.githubusercontent.com/43163156/148064705-40a5f361-aee1-4b7d-b66c-5450a72b974d.png)

@cgewecke  I upgraded the hardhat-gas-reporter to version 1.0.6 and added multiple test cases, but it still doesn’t show the price.

**Comment by cgewecke** [comment] 2022-01-04 14:19
@Rhynie If you push your project to a public repository on Github and send me a link I will take a look and try to debug.

**Comment by Rhynie** [comment] 2022-01-04 14:41
@cgewecke https://github.com/Rhynie/hardhat-demo

**Comment by Rhynie** [comment] 2022-01-04 15:47
> 

Thank you for your help.

**Comment by zjy-1998** [comment] 2022-09-22 09:17
> > 
> 
> ![image](https://user-images.githubusercontent.com/43163156/148063282-f85d12bd-4484-45d0-8999-7d2d31eb6f5e.png) ![image](https://user-images.githubusercontent.com/43163156/148063407-4a825cda-7b43-423b-a88d-588d75aa72a5.png)
> 
> This is my configuration file.

I also had a similar problem, missing the price data in the report. I have put my keys in the configuration file like the picture above, but the account page of coinmarketcap shows that I have not called my API even once. Really hope to get help

**Comment by theirrationalone** [comment] 2022-10-04 21:38
make sure to pass coinmarketcap api key correctly, if done and still getting problems, delete gasReporter property then and add it again :) kind of refresh after that re-deploy/re-test your contract(s)! hope it will help?...
```solidity
gasReporter: {
        enabled: true,
        noColors: true,
        coinmarketcap: COINMARKETCAP_API_KEY,       // use constants/enums ...
        currency: "USD",
        token: "ETH",
        outputFile: "gas-reporter.txt",
}
```

**Comment by JangoCCC** [comment] 2023-01-09 04:10
got the same situation in my project, COINMARKETCAP_API_KEY set properly and my hardhat-gas-reporter version is 1.0.9.

**Comment by lucgerrits** [comment] 2023-12-03 16:10
Same for me, using a correct coinmarketcap key and :
```
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomicfoundation/hardhat-chai-matchers": "^2.0.2",
    "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "chai": "^4.3.10",
    "ethers": "^6.8.1",
    "hardhat": "^2.19.0",
    "hardhat-gas-reporter": "^1.0.9"
  },
  "dependencies": {
    "solidity-coverage": "^0.8.5"
  }
}
```
It just shows empty values for the costs like OP issue.

**Comment by chapma26** [comment] 2024-01-10 18:51
Yep, not working for me, either.

![Screenshot from 2024-01-10 13-50-35](https://github.com/cgewecke/hardhat-gas-reporter/assets/11208814/c103e992-1f9a-45a8-882b-cb8700b83647)

**Comment by BTBMan** [comment] 2024-08-15 10:51
Not working for me!

<img width="692" alt="image" src="https://github.com/user-attachments/assets/489129b1-6573-4f46-a6de-ab2d4ac1cc5d">
<img width="330" alt="image" src="https://github.com/user-attachments/assets/c60d67ed-47ec-4b50-ae23-8a75b91d3e4d">

**Comment by cgewecke** [comment] 2024-08-15 15:41
@BTBMan Etherscan recently began requiring an api key to get live gas price data for the Ethereum network. Could you try:
+ making sure you've updated the plugin to the latest release (v2.2.1)
+ getting a free tier Etherscan api key here: https://docs.etherscan.io/getting-started/viewing-api-usage-statistics
+ configuring as below:
```ts
const config: HardhatUserConfig = {
  gasReporter: {
    enabled: true,
    outputFile: 'gas-report.txt',
    L1Etherscan: "ABC...",
    coinmarketcap: "abc...",
  }
}
```

The default settings for the `token` and `currency` options are already `ETH` and `USD` so you shouldn't need to set those.  You also shouldn't need to set the `noColors` option anymore when writing to file.

**Comment by BTBMan** [comment] 2024-08-15 17:14
@cgewecke Aha, I don't know how I installed version 1.0.x 😥,  It works after updating to the latest! Thanks a lot.

**Comment by wasim007choudhary** [comment] 2024-12-14 13:51
```
  gasReporter: {
    //apiKey: ETHERSCAN_API_KEY,
    enabled: true,
    outputFile: "gas-report.txt",
    //noColours: true,
    //currency: "USD",
    //token: "Eth"
    L1Etherscan: ETHERSCAN_API_KEY,
    coinmarketcap: COINCAP_API_KEY,
  },
```
comment out as they come packed in with hardhtat toolbox ```//require("hardhat-gas-reporter"); alredady built in hardhat toolboox
//require("@nomiclabs/hardhat-etherscan"); hardhat toolbox is enough```
this is my setup  and it works like a charm.
include booth the apis ethrscan key and coincap key and name em === same opr else itll will throw you the same error.
lemme know if it works
